#!/usr/bin/env bash

for d in {1..3}; do
    bspc desktop $d -m DP-1-1
    sleep 0.2
done

for d in {4..6}; do
    bspc desktop $d -m DP-1-2
    sleep 0.2
done

MONITORS="DP-1-1 DP-1-2" $HOME/.config/polybar/launch.sh
