#!/usr/bin/env bash

log() {
    logger -t autorandr "$1"
}

for d in {1..3}; do
    log "bspc desktop $d -m DP-1-1"
    bspc desktop $d -m DP-1-1
done

for d in {4..6}; do
    log "bspc desktop $d -m DP-1-2"
    bspc desktop $d -m DP-1-2
done

log "bspc monitor eDP-1 -r"
bspc monitor eDP-1 -r

MONITORS="DP-1-1 DP-1-2" $HOME/.config/polybar/launch.sh
