#! /bin/sh

start() {
    $(pgrep $1)
    if [ $? -eq 0 ]; then
        pkill $1
    fi

    exec "$@" &
}

start sxhkd &

if [ "$(hostname)" == "yoda" ]; then
    bspc monitor -d 1 2 3 4 5 6
fi

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

if [ "$(hostname)" == "yoda" ]; then
    bspc rule -a firefox desktop=1
    bspc rule -a URxvt desktop=2 follow=on
fi

start compton 
# wal must be executed BEFORE the polybar launching to retrieve the right color (for the polybar transparency)
wal -R
$HOME/.config/polybar/start.sh &

if [ "$(hostname)" == "yoda" ]; then
    start nextcloud --background
    start protonmail-bridge --no-window
    start nm-applet 
    start dunst
fi

