#! /bin/sh

start() {
    $(pgrep $1)
    if [ $? -eq 0 ]; then
        pkill $1
    fi

    exec "$@" &
}

start sxhkd

bspc monitor -d 1 2 3 4 5 6

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop=1
bspc rule -a Chromium desktop=2
bspc rule -a Pavucontrol state=floating
bspc rule -a TelegramDesktop desktop=3 state=pseudo_tiled
bspc rule -a zoom desktop=3 state=pseudo_tiled
bspc rule -a Slack desktop=3 state=pseudo_tiled
bspc rule -a URxvt desktop=4 follow=on
bspc rule -a code-oss desktop=5

start numlockx
start compton 
# wal must be executed BEFORE the polybar launching to retrieve the right color (for the polybar transparency)
wal -R

if [ "$(hostname)" == "soad" ]; then
    autorandr --force -c
else
    $HOME/.config/polybar/launch.sh &
fi

start dunst
start nm-applet 

if [ "$(hostname)" == "yoda" ]; then
    start nextcloud --background
    start protonmail-bridge --no-window
elif [ "$(hostname)" == "soad" ]; then
    start blueman-applet
fi

